Import numpy with any convenient name,
for Example Import numpy as np

Single Dimensional array:

In [ ]:
import numpy as np
print('Single Dimensional Array:')
x = np.array([1,2,3,4,5])
print(x)

Single Dimensional Array:
[1 2 3 4 5]


Another Example,

In [ ]:
print('Another Example of Single Dimensional Array:')
y = np.array([0,2,4,6,16,32,64])
print(y)

Another Example of Single Dimensional Array:
[ 0  2  4  6 16 32 64]


Two Dimensional Array:

In [ ]:
print('Two Dimensional Array:')
A = ([[1,2,3,4],[5,6,7,8]])
print("This is a Two Dimensional Array")
print(A)

Two Dimensional Array:
This is a Two Dimensional Array
[[1, 2, 3, 4], [5, 6, 7, 8]]


Another Example,

In [ ]:
print('Another Example of Two Dimensional Array:')
A = ([[10,20,30,40],[50,60,70,80]])
print(A)

Another Example of Two Dimensional Array:
[[10, 20, 30, 40], [50, 60, 70, 80]]


Three Dimensional Array:

In [ ]:
B = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(B)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


To Find dimension:
Let's take the Three dimensional Array that we created and named as B,


In [ ]:
print('Dimension of B Array:',B.ndim)

Dimension of B Array: 3


To Find number of elements and shape:
Let's take the same B array,


In [ ]:
print('Size of B Array:',B.size)
print('Shape of B Array:',B.shape)

Size of B Array: 9
Shape of B Array: (1, 3, 3)


Demonstrating Reshape:


In [ ]:
X = np.arange(10) 
print(X)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print("Reshaping X with 2 rows and 5 columns")
print(X.reshape(2,5))

Reshaping X with 2 rows and 5 columns
[[0 1 2 3 4]
 [5 6 7 8 9]]


Array Indexing:

In [ ]:
X = np.arange(10)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
X = np.arange(10)
print(X)
print(X[:1])
print(X[-1])
print(X[:-1])
print(X[-1:])
print(X[1:5:2]) #1 to 5 with step = 2

[0 1 2 3 4 5 6 7 8 9]
[0]
9
[0 1 2 3 4 5 6 7 8]
[9]
[1 3]


Multi Dimensional arrays:

In [ ]:
x1 = np.random.randint(10, size=(3,4,5)) #No. of arrays, No of Rows, No of columns
print('Before Indexing:\n','\n',x1,'\n')
print('After Indexing:\n')
print(x1[1:3],'\n')
print('Same as the size we gave for creating this arrays (Size = 3,4,5) \n',x1.shape)
print('row * column = 4 * 5 and there are 3 arrays then 3 * 20,\n Size -->',x1.size)

Before Indexing:
 
 [[[4 7 1 4 0]
  [0 9 8 1 7]
  [1 7 5 2 8]
  [6 6 1 1 0]]

 [[5 6 6 2 2]
  [3 3 1 7 1]
  [8 0 2 7 6]
  [8 4 4 4 3]]

 [[4 3 8 4 4]
  [5 2 1 4 5]
  [2 5 2 4 0]
  [4 1 7 0 8]]] 

After Indexing:

[[[5 6 6 2 2]
  [3 3 1 7 1]
  [8 0 2 7 6]
  [8 4 4 4 3]]

 [[4 3 8 4 4]
  [5 2 1 4 5]
  [2 5 2 4 0]
  [4 1 7 0 8]]] 

Same as the size we gave for creating this arrays (Size = 3,4,5) 
 (3, 4, 5)
row * column = 4 * 5 and there are 3 arrays then 3 * 20,
 Size --> 60
