## 1.2 Working with Numpy Arrays - Array Operation

---



***Single Dimensional array:***

***Import the Numpy module***

In [ ]:
import numpy as np

***Array Creation:***
*Single Dimensional Array:*

In [ ]:
x = np.array([1,2,3,4,5])
print('Array Elements are:',x)

Array Elements are: [1 2 3 4 5]


***Array Creation:*** *Two Dimensional Array:*

In [ ]:
A = ([[1,2,3,4],[5,6,7,8]])
print("Two Dimensional Array is:")
print(A)

Two Dimensional Array is:
[[1, 2, 3, 4], [5, 6, 7, 8]]


***Array Operations:*** *Arithmetic Operations (Addition, Subraction, Dot, Multiplication)*

In [ ]:
c = ([5,6,7,8])
d = ([0,2,5,8])
print('Addition:',np.add(c,d))
print('Subtract:',np.subtract(c,d))
print('\nDot Operator multiplies 1st element from 1 array to the 1st element in 2nd array and vice versa\n',np.dot(c,d))

print('Multiplication:',np.multiply(c,d))

Addition: [ 5  8 12 16]
Subtract: [5 4 2 0]

Dot Operator multiplies 1st element from 1 array to the 1st element in 2nd array and vice versa
 111
Multiplication: [ 0 12 35 64]


***Aggregate Functions:*** *Sum, Average, Product, Transpose, Min and Max*

In [ ]:
x = np.array([1,2,3,4,5,6])
print('Sum:',np.sum(x))
print('Minimum:',np.min(x))
print('Maximum:',np.max(x))
print('Product:',np.prod(x))
print('Sorted:',np.sort(x))
print('Transpose:',x.T)

Sum: 21
Minimum: 1
Maximum: 6
Product: 720
Sorted: [1 2 3 4 5 6]
Transpose: [1 2 3 4 5 6]


***Sorting Array:*** *Sorting means putting elements in an ordered sequence*

In [ ]:
arr = np.array([3, 2, 0, 1])
arr1 = np.array(['z', 'h', 'a'])
print(np.sort(arr))
print(np.sort(arr1))

[0 1 2 3]
['a' 'h' 'z']


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


***Searching Arrays:*** *You can search an array for a certain value, and return the indexes that get a match.*

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


***Array Joining***: *Joining two arrays in a single array*

***We use concatenate for Joining the arrays***

In [ ]:
x=np.array([1,2,3,4])
y=np.array([5,6,7,8])
z=np.concatenate((x,y))
z

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,20]])  
z=np.concatenate((x,y))  
z

array([[ 1,  2],
       [ 3,  4],
       [12, 20]])

In [ ]:
print('With Axis 0')
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y), axis=0)
z

With Axis 0


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
print('With Axis 1')
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.concatenate((x, y), axis=1)
z

With Axis 1


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

***Other Array Operations:***

***Joining Arrays Using Stack Functions*** ***:*** *Stacking is same as concatenation, the only difference is that stacking is done along a new axis.*

In [ ]:
x= np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y), axis=0)
print(z)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
x= np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.stack((x, y), axis=1)
print(z)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
x= np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("Using 'hstack'")
z = np.hstack((x, y))
print(z)

Using 'hstack'
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
x= np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("Using 'vstack'")
z = np.vstack((x, y))
print(z)

Using 'vstack'
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


***Using "dstack"***

In [ ]:
x= np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print("Using 'dstack'")
z = np.dstack((x, y))
print(z)

Using 'dstack'
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


***Array Split:*** *Splitting is reverse operation of Joining.*

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
n = np.array_split(arr, 6) #split into 6 arrays
n

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [ ]:
print("If the array has less elements than required, it will adjust from the end accordingly\n")
a = np.array([1, 2, 3, 4, 5, 6])
n = np.array_split(arr, 5) #split into 6 arrays
n

If the array has less elements than required, it will adjust from the end accordingly



[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.vsplit(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
a = np.arange(12.0).reshape (2,2,3)
print(a,'\n')
newarr = np.dsplit(a, 3)
print(newarr)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]] 

[array([[[0.],
        [3.]],

       [[6.],
        [9.]]]), array([[[ 1.],
        [ 4.]],

       [[ 7.],
        [10.]]]), array([[[ 2.],
        [ 5.]],

       [[ 8.],
        [11.]]])]
