# 1.3 Working with Numpy Array : Fancy Indexing 

---


# **Fancy Indexing**

## Fancy indexing means passing an array of indices to access multiple array elements at once.

Importing the Numpy Module with the Name 

In [ ]:
import numpy as np

Creating the Array

For example, consider the following array:

In [ ]:
rand = np.random.RandomState(42)

a = rand.randint(100, size=10)
print(a)

[51 92 14 71 60 20 82 86 74 74]


 To access Four different elements

In [ ]:
[a[1], a[5], a[7], a[9]]

[92, 20, 86, 74]

We can also pass the indices in the single list to get the output

In [ ]:
i = [1,5,7,9]
a[i]

array([92, 20, 86, 74])

In Fancy Indexing,The Shape of the result reflects the shape of the index array and not reflects the shape of the array being indexed

In [ ]:
i = np.array([[1, 5],
                [9, 7]])
a[i]

array([[92, 20],
       [74, 86]])

Fancy indexing also works in multiple dimensions

In [ ]:
x = np.arange(12).reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Like standard indexing, The First index array refers to the row and The Second array to the column

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
x[row, col]

array([ 2,  5, 11])

In [ ]:
x[row[:, np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

## **Combined Indexing**


Powerful Operations can be Performed by combining the Fancy Indexing with other Indexing Methodes

In [ ]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Combining Fancy indexing and Simple indices

In [ ]:
x[2, [1, 0, 3]]

array([ 9,  8, 11])

Combining Fancy indexing with Slicing

In [ ]:
x[1:, [2, 0, 1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

## **Modifying Values Using Fancy Indexing**

The Fancy Indexing Array is use to Access the Part of The array But,It can be also use to Modify the arrsy

In [ ]:
y = np.arange(10)
i = np.array([2, 1, 8, 4])
y[i] = 99
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


We can use any assignment-type operator for this

For Example :

In [ ]:
y[i] -= 10
print(y)

[ 0 79 79  3 79  5  6  7 79  9]
